apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "komiser.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "komiser.name" . }}
    helm.sh/chart: {{ include "komiser.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "komiser.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
         iam.amazonaws.com/role: {{ .Values.role }}
      labels:
        app.kubernetes.io/name: {{ include "komiser.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.aws.region }}"
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.service.port }}
{{- if .Values.service.nodePort }}
              nodePort: {{ .Values.service.nodePort }}
{{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
